---
title: "Writing Functions in R"
output: learnr::tutorial
runtime: shiny_prerendered
---

## Concept Map

## Learner Persona

## Slides



```{r setup, include = FALSE}
library(learnr)
library(parsons)

knitr::opts_chunk$set(echo = FALSE)
```

## Naming functions

```{r naming}
question(
  "Imagine you're writing a function to convert kilograms to pounds. Which name would you choose for your function?",
  allow_retry = TRUE,
  random_answer_order = TRUE,
  answer("convert_kg_to_lb()", correct = TRUE, message = "Yes! The name is clear as to what it does - converts kilograms to pounds - and reads \"in English\" without ambiguity as to what it does"),
  answer("weight_converter()", message = "This function name does not clearly convey which way the conversion is happening - are pounds being converted to kilograms, or vice versa? What units are used? Ounces? It would likely result in more misuse, or the need to continuously read the documentation."),
  answer("kgtolb()", message = "While this name conveys that kg are being converted to pounds, it is difficult to read all as one word."),
  answer("Kilogram_ToPounds()", message = "This function name combines two popular naming conventions - snake_case and CamelCase. Combining both would likely make it more difficult for a user to remember the function name when the time comes to use it.")
)
```
  
## Writing functions

```{r rearrange-function}
question_parsons(
  initial = c(
    "}",
    "x_length <- length(x)",
    "last_element <- function(x) {",
    "x[[x_length]]"
  ),
  pass_if(
    c(
      "last_element <- function(x) {",
      "x_length <- length(x)",
      "x[[x_length]]",
      "}"
    )
  )
)
```

## Function Arguments

```{r arguments-order}
question("Imagine you want to write a function that returns the mean and variance of a vector, with the option to remove `NA` values. What arguments would you include in the function, and in what order? If it is helpful, run `?mean` or `?var` to look at the arguments they use.",
  allow_retry = TRUE,
  random_answer_order = TRUE,
  answer("x, na.rm", correct = TRUE, message = "Yes - the same arguments as `mean` and `var`, in the same order"),
  answer("x, y, na.rm", message = "No - `y` is not needed to get the var of a single vector - only for calculating the covariance."),
  answer("na.rm, x", message = "Right arguments, wrong order - confusing for people who are used to mean and var."),
  answer("x, remove.na", message = "No - different \"name\" for na.rm so would be confusing and hard to remember the syntax.")
)
```

```{r argument-default}
question("What would you use as the default value for `na.rm` in `mean_and_var`? Again, if it's helpful, look at `?mean` and `?var`.",
  allow_retry = TRUE,
  random_answer_order = TRUE,
  answer("`FALSE`", correct = TRUE, message = "Yes! This is the value used by both `mean` and `var` - for consistency, it is good to use the same default value so that users expect the same behaviour."),
  answer("`TRUE`", message = "No! `mean` and `var` both use `na.rm = FALSE` as the default, so it may be confusing and inconsistent for users if `mean_and_var` removes the `NA`s by default.")
)
```

## Return Values

Multiple values

Guess what function returns


Here is the start of a function to return the mean and variance of a vector, x. How would you return both values?

```{r, eval = FALSE}
mean_and_var <- function(x) {
   x_mean <- mean(x)
   x_var <- var(x)
   
   return(____)
}
```

```{r, eval = FALSE}
mean_and_var <- function(x, na.rm) {
   x_mean <- mean(x, na.rm)
   x_var <- var(x, na.rm)
   
   return(
      list(mean = x_mean,
           var = x_var)
   )
}

mean_and_var(1:10)
```

---


